### ISSUE TITLE
submodules aren't working

### ISSUE THREAD

**Issue by bruce-lumo** [bitrise-io/build.issues#3] opened 2016-11-18 00:54 UTC
# Bitrise Build Issue Report template

## Description of the issue

I have a swift project with two submodules. On my workstation gitkraken pulls proj and submodules and builds just fine with xcode 8.1 and Sierra. When I try to do my deploy workflow it fails trying to import my frameworks in my submodules.

I hope you can help, your service looks good, but if I can't get it working soon I'll have to move on.

## Environment:

Where did the issue happen?

- If on Bitrise.io: which stack?

https://www.bitrise.io/app/4b5e654d2c31a54c#/builds

Which build Step causes the issue and which version of the step?

Create the Archive ...
  $ set -o pipefail && xcodebuild -workspace "LumoLift.xcworkspace" -scheme "LumoLift" archive -archivePath "/var/folders/90/5stft2v13fb_m_gv3c8x9nwc0000gn/T/tmp.VSr6HETe/LumoLift.xcarchive" | tee /var/folders/90/5stft2v13fb_m_gv3c8x9nwc0000gn/T/tmp.udauqwL7/raw-xcodebuild-output.log | xcpretty

▸ Aggregate LumoLift/BuildNumberGenerator [Release]
▸ Check Dependencies
▸ Running script 'Run Script'
▸ Building LumoLift/LumoLift [Release]
▸ Check Dependencies
▸ Preprocessing LumoLift/Info.plist

❌  /Users/vagrant/git/LumoLift/LumoLift/Settings/LLSensorDetailsViewController.swift:10:8: no such module 'LumoBluetooth'

import LumoBluetooth;
       ^

** ARCHIVE FAILED **

The following build commands failed:
	CompileSwift normal arm64
	CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler
(2 failures)
If you can't find the reason of the error in the log, please check the raw-xcodebuild-output.log
The log file is stored in $BITRISE_DEPLOY_DIR, and its full path
is available in the $BITRISE_XCODE_RAW_RESULT_TEXT_PATH environment variable
|                                                                              |
+---+---------------------------------------------------------------+----------+
| x | xcode-archive@1.10.1 (exit code: 1)                           | 65 sec   |
+---+---------------------------------------------------------------+----------+
| Issue tracker: https://github.com/bitrise-io/steps-new-xcode-archive/issues  |
| Source: https://github.com/bitrise-io/steps-new-xcode-archive                |
+---+---------------------------------------------------------------+----------+

## Reproducibility

[fd6ae7e85fb332e3.log.zip](https://github.com/bitrise-io/build.issues/files/598812/fd6ae7e85fb332e3.log.zip)

It happens each time I run the deploy workflow. Re-running it does not help.

### Linux/Android stack builds

- Can it be reproduced by running the build locally with Docker (using the same docker images we use on bitrise.io), after doing a clean git clone (git clone the repository, into a new directory, somewhere on your Mac/PC) and running the build from there? (Related guide: http://blog.bitrise.io/2016/08/08/debug-your-android-linux-builds-locally-with-docker.html )

### Other stacks

- Can it be reproduced by running the build locally with our CLI ( https://www.bitrise.io/cli ), after doing a clean git clone (git clone the repository, into a new directory, somewhere on your Mac/PC) and running the build from there with the CLI?

## Build log

Please attach the build log (you can download the build log from the build's page,
once the build is finished, using the "Download log" button - floating at the bottom right corner of the log viewer),
__or if you can't attach the whole log__ then the related step's build log, or as much as you can share.

**Comment by viktorbenei** [comment] 2016-11-18 00:59
Please fill out the reproduction section for your stack:

-> Other stacks

Can it be reproduced by running the build locally with our CLI ( https://www.bitrise.io/cli ), after doing a clean git clone (git clone the repository, into a new directory, somewhere on your Mac/PC) and running the build from there with the CLI?

**Comment by viktorbenei** [comment] 2016-11-18 01:00
My guess, based on the log is that your submodule is not getting pulled. Maybe it's not configured properly, or at least not for the branch you tried to build.

**Comment by viktorbenei** [comment] 2016-11-22 14:31
I'll close this issue for now because of lack of information - @bruce-lumo if you can provide more info / try the reproduction I mentioned above, just reply here and I'll reopen the ticket.

**Closed by viktorbenei** 2016-11-22 14:31 UTC
Labels: waiting for reply
