### ISSUE TITLE
[Android-Build NDK] CMake license problem

### ISSUE THREAD

**Issue by mbertin** [bitrise-io/build.issues#33] opened 2016-12-13 10:22 UTC
# Bitrise Build Issue Report template

## Description of the issue

I got this message from gradle when I want to compile 

Caused by: java.lang.RuntimeException: You have not accepted the license agreements of the following SDK components:
[CMake 3.6.3155560].
Before building your project, you need to accept the license agreements and complete the installation of the missing components using the Android Studio SDK Manager.

## Environment:

__Where did the issue happen?__

It happen with the gradle command assembleRelease(and other type)

_If on Bitrise.io: which stack? If not on Bitrise.io: on what operating system? (Plus any other information you can share)_ Linux Android

__Which build Step causes the issue and which version of the step?__

unit test => gradle compilation 
[bitrise-build-09e4d25b16c46b8e.txt](https://github.com/bitrise-io/build.issues/files/648582/bitrise-build-09e4d25b16c46b8e.txt)

## Reproducibility

- _Does a "Rebuild" help? (You can trigger a rebuild from the Build's page, by clicking the "Rebuild" button in the top right corner of a finished build)_ : NO
- _Does a rebuild without caches help? (You can remove the `Cache:Pull` and `Cache:Push` steps temporarily to not to use the cache, or [you can *delete all the caches* on the `Settings` tab of the app](https://bitrise-io.github.io/devcenter/caching/about-caching/#downloading-and-deleting-caches)._ : NO
- _If you have multiple different build configurations (workflows), does the issue affect all/more than one?_ : YES
- _If it's an issue which happens sporadically, what's the frequency? (e.g. Once a day ; about x% of the builds)_ : every builds
- _Does upgrading the build Step to the latest version help?_ : YES/NO
- _When did the issue start?_ :

### Linux/Android stack builds

_Can it be reproduced by running the build locally, **after doing a clean git clone (git clone the repository, into a new directory, somewhere on your Mac/PC)** and running the build from there with the Bitrise CLI ( https://www.bitrise.io/cli )? If no, can it be reproduced with Docker (using the same docker images / environment we use on bitrise.io)? Related guide: https://bitrise-io.github.io/devcenter/docker/run-your-build-locally-in-docker/ ._

### Other stacks

_Can it be reproduced by running the build locally with our CLI ( https://www.bitrise.io/cli ), **after doing a clean git clone (git clone the repository, into a new directory, somewhere on your Mac/PC)** and running the build from there with the CLI ( https://www.bitrise.io/cli )?_

## Build log

_Please attach the build log (you can download the build log from the build's page,
once the build is finished, using the "Download log" button - floating at the bottom right corner of the log viewer),
**or if you can't attach the whole log** then send the **full log** through a private channel (e.g. email - https://www.bitrise.io/contact ), **with a link to the related GitHub issue**._

**Comment by viktorbenei** [comment] 2016-12-13 12:28
Hi,

You have to copy/provide the licenses for the packages which are not preinstalled but required/installed for your project or build.
You can find more information here: http://devcenter.bitrise.io/android/frequent-android-issues/#alternative-solution-for-the-license-error

Let us know whether that helps!

**Comment by mbertin** [comment] 2016-12-15 15:58
Hi @viktorbenei,
Effectively it helps me but now i'm face to 

`Caused by: java.lang.NullPointerException
	at com.android.builder.sdk.DefaultSdkLoader.installSdkTool(DefaultSdkLoader.java:570)` 

for running the android unit test.

I join the log file 
[77fec3a41a51affe.txt](https://github.com/bitrise-io/build.issues/files/655114/77fec3a41a51affe.txt)

Do I miss something else ? 
Because before the tests was passing this step.

**Comment by viktorbenei** [comment] 2016-12-15 16:00
Try to do a clean git clone, into a new directory on your Mac/PC, and run the `gradlew` command there. Do you get the same error?

**Comment by mbertin** [comment] 2016-12-15 16:07
I got this 

`FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':app'.
> SDK location not found. Define location with sdk.dir in the local.properties file or with an ANDROID_HOME environment variable.`

In Android studio I have the local.properties but it aim my local SDK, I was thinking that the Bitrise Machine has 'ANDROID_HOME'  env variable ?

**Comment by viktorbenei** [comment] 2016-12-15 16:09
The Bitrise Android/Xamarin stacks do have the `ANDROID_HOME` env set.

**Comment by viktorbenei** [comment] 2016-12-15 16:10
But locally you might not - in that case set it with `export ANDROID_HOME=/path/to/android/sdk` before running `gradlew`

**Comment by mbertin** [comment] 2016-12-15 16:11
I have done this and now it failed because it doesn't found.

`> NDK not configured.
  Download it with SDK manager.)`

**Comment by viktorbenei** [comment] 2016-12-15 16:13
Then set the `ANDROID_NDK_HOME` var too, like the `ANDROID_HOME` one

**Comment by mbertin** [comment] 2016-12-15 16:15
Then it worked BUILD SUCCESSFUL

**Comment by mbertin** [comment] 2016-12-15 16:18
So I have to define ANDROID_NDK_HOME and ANDROID_HOME with a script ? 
Can you give the right paths ?

**Comment by viktorbenei** [comment] 2016-12-15 16:21
No, you don't have to define those, those are already set.

Can you try to build on a different Mac/PC? This error is usually a project configuration issue, but hard to tell what causes it - on your own Mac/PC you might have a cached version of a resource which makes it pass, which is not available in your repo/on another Mac/PC.

See these for example:

- http://stackoverflow.com/questions/40108471/java-lang-nullpointerexception-no-error-message-apk-building
- http://stackoverflow.com/questions/39183674/java-lang-nullpointerexception-no-error-message
- http://stackoverflow.com/questions/39226834/errorjava-lang-nullpointerexception-no-error-message

And https://www.google.com/?gfe_rd=cr&ei=5MJSWOPpKaat8wfBvIfoCQ&gws_rd=cr&fg=1#safe=off&q=java.lang.NullPointerException+(no+error+message) in general

**Comment by mbertin** [comment] 2016-12-16 10:53
I try to do it on a different Mac, it works, the Mac didn't have java installed on it but after installing it and the SDK, NDK (exporting ANDROID_NDK_HOME and ANDROID_HOME), i start the ./gradlew inside the freshly cloned project and it worked... I don't know what to do because, this can eliminate a problem of gradle cache or misconfiguration of the project.

**Comment by viktorbenei** [comment] 2016-12-16 11:02
Which Java version do you use?

**Comment by mbertin** [comment] 2016-12-16 11:15
JDK 1.8

**Comment by mbertin** [comment] 2016-12-16 11:16
` java -version 
java version "1.8.0_92"
Java(TM) SE Runtime Environment (build 1.8.0_92-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.92-b14, mixed mode)
`

**Comment by viktorbenei** [comment] 2016-12-16 11:22
Did you try to do a build with Docker, as described here https://bitrise-io.github.io/devcenter/docker/run-your-build-locally-in-docker/ ? It should definitely help in reproducing the issue locally.

Is there any way we could reproduce this issue? e.g. a sample repository you could share with us?

**Comment by mbertin** [comment] 2016-12-16 11:23
No sorry it's my company app so I can't but I will try to do it locally on the docker machine. I will let you know. Thank you for your time ! :)

**Comment by viktorbenei** [comment] 2016-12-16 12:50
Sure, let us know how it goes, and if we can help with anything!

**Comment by viktorbenei** [comment] 2016-12-21 09:57
Closing as we did not receive a reply - @mbertin please let us know if we can help with anything and we'll reopen this issue!

**Closed by viktorbenei** 2016-12-21 09:57 UTC
Labels: configuration issue, waiting for reply

**Comment by mbertin** [comment] 2017-01-16 16:01
Hello @viktorbenei,
I try to do it locally and I have met this error...
In order to locate the problem, i started a new project with this gradle file 


```
apply plugin: 'com.android.application'

android {
    compileSdkVersion 25
    buildToolsVersion "25.0.2"
    defaultConfig {
        applicationId "com.igraal.testbitrise"
        minSdkVersion 16
        targetSdkVersion 25
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
        externalNativeBuild {
            cmake {
                cppFlags ""
            }
        }
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    
    externalNativeBuild {
        cmake {
            path "CMakeLists.txt"
        }
    }
}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    androidTestCompile('com.android.support.test.espresso:espresso-core:2.2.2', {
        exclude group: 'com.android.support', module: 'support-annotations'
    })
    compile 'com.android.support:appcompat-v7:25.1.0'
    testCompile 'junit:junit:4.12'
}
```

I fix the license problem by copying pasting my proper licenses following the bitrise doc about it.
And I have the same bug, I think the problem is about the cmake command install that failed on the docker... I don't see how to fix it... Do you have any project that use cmake working on docker ? 

This is the new repository if you want to test, it's just a new project created by Android studio with the android-licenses folder
https://github.com/mbertin/testBitriseAndroid

**Comment by mbertin** [comment] 2017-01-16 16:20
I notice that by commenting the externalNativeBuild part in the gradle file, it works !

**Comment by viktorbenei** [comment] 2017-01-16 16:22
Good catch @mbertin !

Btw, did you get the __same__ error in this new project?

**Comment by mbertin** [comment] 2017-01-16 16:40
Yes i Got the same error which is 

> A problem occurred configuring project ':app'.
> java.lang.NullPointerException (no error message)

**Comment by mbertin** [comment] 2017-01-16 16:41
and the stacktrace from gradle : 

> 
* Exception is:
org.gradle.api.ProjectConfigurationException: A problem occurred configuring project ':app'.
        at org.gradle.configuration.project.LifecycleProjectEvaluator.addConfigurationFailure(LifecycleProjectEvaluator.java:79)
        at org.gradle.configuration.project.LifecycleProjectEvaluator.notifyAfterEvaluate(LifecycleProjectEvaluator.java:74)
        at org.gradle.configuration.project.LifecycleProjectEvaluator.evaluate(LifecycleProjectEvaluator.java:61)
        at org.gradle.api.internal.project.AbstractProject.evaluate(AbstractProject.java:540)
        at org.gradle.api.internal.project.AbstractProject.evaluate(AbstractProject.java:93)
        at org.gradle.execution.TaskPathProjectEvaluator.configureHierarchy(TaskPathProjectEvaluator.java:47)
        at org.gradle.configuration.DefaultBuildConfigurer.configure(DefaultBuildConfigurer.java:35)
        at org.gradle.initialization.DefaultGradleLauncher$2.run(DefaultGradleLauncher.java:124)
        at org.gradle.internal.Factories$1.create(Factories.java:22)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:91)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:53)
        at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:121)
        at org.gradle.initialization.DefaultGradleLauncher.access$200(DefaultGradleLauncher.java:32)
        at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:98)
        at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:92)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:91)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:63)
        at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:92)
        at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:83)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProcessBuildActionExecuter.java:99)
        at org.gradle.tooling.internal.provider.ExecuteBuildActionRunner.run(ExecuteBuildActionRunner.java:28)
        at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:48)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:30)
        at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:81)
        at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:46)
        at org.gradle.launcher.daemon.server.exec.ExecuteBuild.doBuild(ExecuteBuild.java:52)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.WatchForDisconnection.execute(WatchForDisconnection.java:37)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.ResetDeprecationLogger.execute(ResetDeprecationLogger.java:26)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.RequestStopIfSingleUsedDaemon.execute(RequestStopIfSingleUsedDaemon.java:34)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:74)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:72)
        at org.gradle.util.Swapper.swap(Swapper.java:38)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput.execute(ForwardClientInput.java:72)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.health.DaemonHealthTracker.execute(DaemonHealthTracker.java:47)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.LogToClient.doBuild(LogToClient.java:60)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment.doBuild(EstablishBuildEnvironment.java:72)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.health.HintGCAfterBuild.execute(HintGCAfterBuild.java:41)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy$1.run(StartBuildOrRespondWithBusy.java:50)
        at org.gradle.launcher.daemon.server.DaemonStateCoordinator$1.run(DaemonStateCoordinator.java:237)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
        at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
Caused by: java.lang.NullPointerException
        at com.android.builder.sdk.DefaultSdkLoader.installSdkTool(DefaultSdkLoader.java:570)
        at com.android.build.gradle.internal.SdkHandler.installCMake(SdkHandler.java:300)
        at com.android.build.gradle.tasks.ExternalNativeJsonGenerator.create(ExternalNativeJsonGenerator.java:626)
        at com.android.build.gradle.internal.TaskManager.createExternalNativeBuildJsonGenerators(TaskManager.java:1225)
        at com.android.build.gradle.internal.ApplicationTaskManager$11.call(ApplicationTaskManager.java:219)
        at com.android.build.gradle.internal.ApplicationTaskManager$11.call(ApplicationTaskManager.java:216)
        at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:156)
        at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:120)
        at com.android.build.gradle.internal.ApplicationTaskManager.createTasksForVariantData(ApplicationTaskManager.java:214)
        at com.android.build.gradle.internal.VariantManager.createTasksForVariantData(VariantManager.java:485)
        at com.android.build.gradle.internal.VariantManager$3.call(VariantManager.java:293)
        at com.android.build.gradle.internal.VariantManager$3.call(VariantManager.java:290)
        at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:156)
        at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:120)
        at com.android.build.gradle.internal.profile.SpanRecorders.record(SpanRecorders.java:44)
        at com.android.build.gradle.internal.VariantManager.createAndroidTasks(VariantManager.java:286)
        at com.android.build.gradle.BasePlugin$11.call(BasePlugin.java:688)
        at com.android.build.gradle.BasePlugin$11.call(BasePlugin.java:685)
        at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:156)
        at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:120)
        at com.android.build.gradle.BasePlugin.createAndroidTasks(BasePlugin.java:683)
        at com.android.build.gradle.BasePlugin$10.call(BasePlugin.java:608)
        at com.android.build.gradle.BasePlugin$10.call(BasePlugin.java:605)
        at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:156)
        at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:120)
        at com.android.build.gradle.BasePlugin.lambda$createTasks$1(BasePlugin.java:603)
        at org.gradle.internal.event.BroadcastDispatch$ActionInvocationHandler.dispatch(BroadcastDispatch.java:93)
        at org.gradle.internal.event.BroadcastDispatch$ActionInvocationHandler.dispatch(BroadcastDispatch.java:82)
        at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:44)
        at org.gradle.internal.event.BroadcastDispatch.dispatch(BroadcastDispatch.java:79)
        at org.gradle.internal.event.BroadcastDispatch.dispatch(BroadcastDispatch.java:30)
        at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
        at com.sun.proxy.$Proxy11.afterEvaluate(Unknown Source)
        at org.gradle.configuration.project.LifecycleProjectEvaluator.notifyAfterEvaluate(LifecycleProjectEvaluator.java:67)
        ... 52 more

**Comment by viktorbenei** [comment] 2017-01-16 17:04
And without the `externalNativeBuild` part it builds correctly & generates the right APK?

**Comment by mbertin** [comment] 2017-01-17 09:10
Yes it builds and generates the APK.

**Comment by viktorbenei** [comment] 2017-01-17 09:16
Good catch @mbertin and thanks for sharing the info!

I wonder why `externalNativeBuild` makes it fail though..

**Comment by mbertin** [comment] 2017-01-18 12:57
@viktorbenei I don't understand because on mac it works... Maybe it's the version of GCC or something else. Let me know if you find the solution.

**Comment by viktorbenei** [comment] 2017-01-18 14:21
Sure, we definitely will @mbertin ! Thanks again for the infos! ;)

**Comment by mbertin** [comment] 2017-01-31 15:05
Hi @viktorbenei !
Do you have any news about my issue ?

**Comment by viktorbenei** [comment] 2017-01-31 15:08
We didn't have the time to explore this, mainly because you said it works correctly if you remove `externalNativeBuild`.

**Comment by mbertin** [comment] 2017-01-31 15:16
Yes but I need it for my company because now we can't use bitrise on the Android project...

**Comment by viktorbenei** [comment] 2017-01-31 15:41
I just registered https://github.com/mbertin/testBitriseAndroid on bitrise.io, and I got a green build O_O

**Comment by mbertin** [comment] 2017-01-31 15:42
really ?

**Comment by viktorbenei** [comment] 2017-01-31 15:42
Yeah, but I just checked and you commented out the `externalNativeBuild` bits in the project

**Comment by mbertin** [comment] 2017-01-31 15:43
yes, I let the commit but if you checkout on the previous commit it will failed.

**Comment by mbertin** [comment] 2017-02-02 10:43
Hi @viktorbenei ,
I have found a solution about this problem... I use an older version of gradle 
        classpath 'com.android.tools.build:gradle:2.2.2'
instead of 
        classpath 'com.android.tools.build:gradle:2.2.3'

And the problem is gone.

**Comment by viktorbenei** [comment] 2017-02-02 11:01
Thanks for reporting @mbertin !!

Hmm.. That's super strange, especially because the project did work on my Mac too, without any change, full clean clone etc.

I'll still try to dig into this, to see if this might be related to how the NDK is installed in the docker image. I suspect that *maybe* it might be related to the pre-installed CMake version: https://github.com/bitrise-docker/android-ndk/blob/master/Dockerfile#L33 - related discussion: https://github.com/bitrise-docker/android-ndk/pull/20

It's quite unfortunate that the `android update sdk` command does not have the CMake package, so that it have to be installed "manually", which is always prone to errors or might break if they decide to change something..

Anyway, thanks again for the info, and I'll try to debug this a bit more. It seems today I'll finally have some time to try to play around with this ;)

**Comment by viktorbenei** [comment] 2017-02-02 17:45
@mbertin you won't believe what the solution is. Simply:

```
rm -rf ${ANDROID_HOME}/cmake
```

To remove the default `cmake` install.

If you do this before the Gradle Runner, then `gradle` will auto install the correct `cmake` version for you.

We'll do a couple of additional tests to see if we should remove the default `cmake` install from the Docker image completely.

**Comment by mbertin** [comment] 2017-02-06 09:46
@viktorbenei really ? Thank you for the time you spent on it ! 
Now I can build ! ^^

**Comment by viktorbenei** [comment] 2017-02-06 10:23
Well, it worked with the sample you provided (if I re-enabled `externalNativeBuild` in my code, where it initially failed, but after `rm -rf ${ANDROID_HOME}/cmake` it worked) :)

Hopefully it will work for other projects too :P

https://github.com/viktorbenei/testBitriseAndroidNDK / https://github.com/viktorbenei/testBitriseAndroidNDK/blob/master/app/build.gradle#L27

**Comment by AthanaseKa** [comment] 2017-02-15 09:37
Hi @viktorbenei,

I'm replacing @mbertin at work. I found out that our builds are not successful since your last update on android-ndk. It is related to CMake again...

I found a workaround by using the previous release of the android-ndk. I hope it will be fixed soon, so I can keep updating my CI.

Just wanted you to know, thanks !

**Comment by viktorbenei** [comment] 2017-02-15 09:51
@AthanaseKa what was the error you got?

**Comment by AthanaseKa** [comment] 2017-02-15 10:39
@viktorbenei I had different errors depending on the gradle version.

With gradle 2.2.1 & 2.2.2:
`> Failed to find CMake.
  Install from Android Studio under File/Settings/Appearance & Behavior/System Settings/Android SDK/SDK Tools/CMake.
  Expected CMake executable at /opt/android-sdk-linux/cmake/bin/cmake.`

With gradle 2.2.3:
`> You have not accepted the license agreements of the following SDK components:
  [CMake 3.6.3155560].
  Before building your project, you need to accept the license agreements and complete the installation of the missing components using the Android Studio SDK Manager.
  Alternatively, to learn how to transfer the license agreements from one workstation to another, go to http://d.android.com/r/studio-ui/export-licenses.html
`

**Comment by viktorbenei** [comment] 2017-02-15 10:44
Can you try to use 2.2.3 and provide the license, as described here http://devcenter.bitrise.io/android/frequent-android-issues/#alternative-solution-for-the-license-error ?

@mbertin 's sample does include this license, if that helps: https://github.com/mbertin/testBitriseAndroid

**Comment by AthanaseKa** [comment] 2017-02-15 12:37
I've added the license and everything appears to be working well.

Thanks a lot !

**Comment by viktorbenei** [comment] 2017-02-15 12:38
Awesome, I'm really glad to hear that @AthanaseKa ! :)
