### ISSUE TITLE
Can't deploy build to iTunes

### ISSUE THREAD

**Issue by EugeneButusov** [bitrise-io/build.issues#43] opened 2016-12-26 12:15 UTC
Can't deploy build to iTunes. The following error happens there:
```
[!] No value found for 'edit_live'
Deploy failed, error: exit status 1
```

All modules are up to date, everything worked before today.

## Environment:

iOS stack, deployment pipeline with deployment to itunes.

Fails at
```
id: deploy-to-itunesconnect-deliver
version: 2.7.3   
``` 
but, actually, it doesn't work for earlier versions too.

## Reproducibility

- Does a "Rebuild" help? (You can trigger a rebuild from the Build's page, by clicking the "Rebuild" button in the top right corner of a finished build)_: NO
- Does a rebuild without caches help? (You can remove the `Cache:Pull` and `Cache:Push` steps temporarily to not to use the cache, or [you can *delete all the caches* on the `Settings` tab of the app](https://bitrise-io.github.io/devcenter/caching/about-caching/#downloading-and-deleting-caches):NO
- If you have multiple different build configurations (workflows), does the issue affect all/more than one? : YES
- Does upgrading the build Step to the latest version help?: NO
- When did the issue start?: Today (Dec, 26th of 2016).

### Other stacks

_Can it be reproduced by running the build locally with our CLI ( https://www.bitrise.io/cli ), **after doing a clean git clone (git clone the repository, into a new directory, somewhere on your Mac/PC)** and running the build from there with the CLI ( https://www.bitrise.io/cli )?_: Honestly, didn't try that, in that case it's better to manually deploy builds with App Loader

## Build log

Not sure I can attach build log as there might be confidential data, and haven't enough time to clean up that log. Thanks for understanding, can share that with secret gist and sending link via Intercom.

**Comment by viktorbenei** [comment] 2016-12-26 14:09
This is a `fastlane` / `deliver` issue - error from the log:

```
[02:59:27]: Making sure the latest version on iTunes Connect matches '1.0' from the ipa file...
[02:59:27]: [32m'1.0' is the latest version on iTunes Connect[0m
[31m
[!] No value found for 'edit_live'[0m
[31;1mDeploy failed, error: exit status 1[0m
```

My guess is that either

a. you did not upload a version manually before (this is noted in the step's description and in the log, that you should upload the first version manually)
b. or it might be an issue related to the iTunes Connect holiday "freeze" (https://developer.apple.com/news/?id=12152016a)

> As a reminder, we will not be accepting new app or app update submissions from December 23 to 27 (Pacific Time), so any releases should be submitted, approved, and scheduled in advance. Other iTunes Connect and developer account features will remain available.

**Comment by EugeneButusov** [comment] 2016-12-26 14:32
yes, @viktorbenei, seems that holidays is the reason, thank you for the hint! Issue can be closed.

**Comment by viktorbenei** [comment] 2016-12-26 14:34
Thanks, I'll close this issue - feel free to ping us if it'd not work after the holiday freeze!

**Comment by viktorbenei** [comment] 2016-12-28 16:58
Actually this seems to be a deliver issue, and should be fixed now - https://github.com/fastlane/fastlane/issues/7680

We might have to update the related Step - will check it ASAP

**Comment by EugeneButusov** [comment] 2016-12-28 17:41
@viktorbenei, using latest version of all steps:
```
[!] No value found for 'edit_live'
Deploy failed, error: exit status 1
```
the same error returns.

**Comment by viktorbenei** [comment] 2016-12-28 18:32
@EugeneButusov can you please send us the build log through email / the onsite chat? Also, which stack do you use?

**Comment by viktorbenei** [comment] 2016-12-28 20:02
It seems the issue still happens for some projects, reopening - but please share a bit more info & your log, as so far I could not reproduce this issue

**Comment by EugeneButusov** [comment] 2016-12-28 20:38
Current stack: Xcode 8.0.x, on OS X 10.11 (El Capitan)
I'll share log privately.

**Comment by viktorbenei** [comment] 2016-12-28 22:15
Successfully reproduced the issue on the stack - related fix PR: https://github.com/bitrise-io/steps-deploy-to-itunesconnect-deliver/pull/20

**Comment by viktorbenei** [comment] 2016-12-28 22:56
New version is ready, will be published in a couple of minutes

**Comment by viktorbenei** [comment] 2016-12-28 23:02
https://github.com/bitrise-io/steps-deploy-to-itunesconnect-deliver/releases/tag/2.8.0 released and shared into the Bitrise StepLib.

All you have to do is to upgrade to this new version (or set the step to "always use latest version"), it'll fix the issue.

Thanks for reporting!

**Closed by viktorbenei** 2016-12-28 23:02 UTC
Labels: waiting for reply

**Comment by EugeneButusov** [comment] 2016-12-28 23:15
@viktorbenei, yes, all works perfect now, thank you very much!
