### ISSUE TITLE
Xamarin.Mac build (using Fake) hanging at codesign stage

### ISSUE THREAD

**Issue by stevenspencer** [bitrise-io/build.issues#12] opened 2016-11-23 16:37 UTC
## Description of the issue

A Xamarin.Mac app is built by running a Fake script that runs MSBuild. When the build gets to the code signing stage, it hangs during execution of codesign.

## Environment:

Where did the issue happen?
This happens on Bitrise.io on the "Xamarin stable with Xcode 8.1 on macOS 10.12 (Sierra)" stack

Which build Step causes the issue and which version of the step?
It fails during the "Script" step version 1.1.0.

## Reproducibility

Rebuilds (with or without cache do not help).
The problem is 100% reproducible.
Upgrading the step does not help.
The last successful build was October 28th 2016.

**Comment by stevenspencer** [comment] 2016-11-23 16:38
This issue can be fixed by changing the stack to:

Xamarin stable with Xcode 7.3 on OSX 10.11 (El Capitan)

**Comment by viktorbenei** [comment] 2016-11-23 16:40
Thank you @stevenspencer for the issue report!

Can you please send us the full build log and link to this issue? Email, onsite chat or any private channel is OK

**Comment by viktorbenei** [comment] 2016-12-05 13:05
The issue is most likely related to code signing / Keychain changes on macOS Sierra, but without more information it's impossible to say.

_For Sierra it's quite important to use a tool which is updated to handle the keychain changes in Sierra, for example our `Certificate and profile installer` step, or else the build can hang at code signing, when Sierra presents a popup which should be manually accepted._

Closing the issue due to not enough information, but of course we're always open to reopen it if further information would be supplied.

**Closed by viktorbenei** 2016-12-05 13:05 UTC
Labels: waiting for reply
